### ISSUE TITLE
pass --features to clippy

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#10]
retrieve --features "foo bar baz" argument and pass it to clippy

A live stream on how to fix #11, which almost requires the same steps as fixing this issue is available here https://youtube.com/watch?v=vrCuCnHYep0 :)

If someone would like to work on it, please let me know and I'll do anything I can to ease the process 🎉

**Comment by undef1nd** [comment]
Hey, 
taking this one :-)

**Comment by o0Ignition0o** [comment]
Hey \o/ help yourself  🎉 
If you have any questions please let me know :)
