### ISSUE TITLE
Remove .clone() when printing the build.stdout output

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#21]
In the [clippy.rs](https://github.com/o0Ignition0o/cargo-scout/blob/master/src/clippy.rs) file, there's a useless `.clone()` call at the end of the Linter's clippy function.

We should switch 
```
println!("{}", String::from_utf8(build.stdout.clone())?);
```
to 
```
println!("{}", String::from_utf8(build.stdout)?);
```

This would be a great way to make a first contribution, and learn how to [fork a project and make your first pull request](https://guides.github.com/activities/forking/).

If anyone has a question, please let me know and I'll gladly help ! :)

**Comment by o0Ignition0o** [comment]
As [dpc pointed out on Twitter](https://twitter.com/DPC_22/status/1200510565384380416?s=20), there is an actual nicer way to handle the printing, which would involve a couple more steps:

- Have a look at how [this command usage example](https://doc.rust-lang.org/std/process/struct.Command.html#examples-12) works.
- Add `use std::io::{self, Write};` to the top of clippy.rs
- Replace the println! statement with `io::stdout().write_all(&build.stdout)?;`
Since we are using the ? operator (more information [here](https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html)) we need to:
- Provide a way to convert from `std::io::Error` to a `crate::error::Error`. Have a look at [error.rs](https://github.com/o0Ignition0o/cargo-scout/blob/master/src/error.rs) 
- Add an `Error::IoError(std::io::Error)` variant, as well as an `impl From<std::io::Error> for Error` block

And voila !

If you have any comment or question about any of the steps involved (or about anything, really... I'm here to help!) please add a comment below and I'll gladly spend a bit of time with you :)

**Comment by undef1nd** [comment]
Heya @o0Ignition0o , is anybody working on this issue? 
I'd like to give it a try some day this week.

**Comment by o0Ignition0o** [comment]
Hey @undef1nd and welcome :)
No one is working on it yet, feel free to take a stab at it :)

If you have any question please let me know, I would be happy to help

**Comment by undef1nd** [comment]
@o0Ignition0o , great, then I'm taking it. Thanks!

**Comment by o0Ignition0o** [comment]
@undef1nd Thanks a lot for your contribution ! 🎉
