### ISSUE TITLE
Parse git diff to display lints on new files

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#30]
For now the git parser only finds edit files, and doesn't handle new files.
This means we miss a lot of possibly lints.
We should be able to parse created files and handle it's lints.

**Comment by cbonaudo** [comment]
I'd like to try to work on this one

**Comment by o0Ignition0o** [comment]
Hey @cbonaudo ! thanks for taking this one :)
If you have any question please let me know !

**Comment by cbonaudo** [comment]
After extensive research, it seems that this is already working

**Comment by o0Ignition0o** [comment]
Ok, sorry for wasting your time, and thank you for having a look at it :D
