### ISSUE TITLE
Pass a cargo.toml file path to the cargo parser

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#31]
The cargo parser is currently using ./Cargo.toml as shown [here](https://github.com/o0Ignition0o/cargo-scout/blob/master/src/main.rs#L51).

It would be nice if we could pass a specific flag like -t and/or --cargo-toml which would allow us to pass a path to the Cargo.toml file, for example: 
`cargo-scout --cargo-toml "./foo/bar/Cargo.toml"`

The steps to reproduce are pretty close from what has been done when adding the --no-default-features flag in #24.

A youtube video explaining how to do so (and actually passing the --no-default-features flag) is available here : https://www.youtube.com/watch?v=vrCuCnHYep0

Feel free to let me know if you have any question :)

**Comment by daubaris** [comment]
Hi! I'd like to tackle this issue!

**Comment by o0Ignition0o** [comment]
Hi @daubaris and thanks for stepping in !
If you have any question please let me know, I would be happy to provide help :)

**Comment by o0Ignition0o** [comment]
Fixed by #34 , thank you @daubaris ! 🎉
