### ISSUE TITLE
git: Only add diffs to .rs files

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#32]
Right now we add any file that has a diff to the list.
We should only add rust files to the list because it will later allow us to run clippy only when needed (and on needed workspace members).

Maybe we could add a continue statement if the file_name doesn't end with .rs ?
https://github.com/o0Ignition0o/cargo-scout/blob/master/src/git.rs#L91

It would be really awesome if we could add a test to it :)

**Comment by oScape** [comment]
Hi @o0Ignition0o, I will take it if possible :)

**Comment by o0Ignition0o** [comment]
Hi @oScape and thank you for grabbing it ! :)

If you have any questions please let me know, I will gladly spend some time with you and walk through the issue :)

**Comment by ebroto** [comment]
I think this one can be closed since #39 was merged
