### ISSUE TITLE
No warnings raised when the binary is run twice

### ISSUE THREAD

**Issue by daubaris** [o0Ignition0o/cargo-scout#36]
`cargo-scout` does not display errors when the binary is run twice without making any changes to the code. 

Steps to reproduce:
1. Violate `clippy::pedantic` rule. (e.g., create a 100 LoC function).
2. Run the program. (It displays the errors correctly)
3. Run the program again without making any changes.

This results in: `No warnings raised by clippy::pedantic in your diff, you're good to go!`. I suppose the expected behavior should be that the program should output the warnings again.

**Comment by ebroto** [comment]
If I'm not mistaken, this is clippy's fault and has been fixed in nightly. See https://github.com/rust-lang/cargo/pull/7450 

I think the change will be available in the next stable version.

**Comment by o0Ignition0o** [comment]
You're correct. Let's leave this issue open until the next stable version is released, so we can make sure it works as expected after the new release :)

**Comment by o0Ignition0o** [comment]
Ok some great news:

I've been able to run `cargo +nightly clippy-preview -Z unstable-options --no-default-features -- -W clippy::pedantic` on neqo, and it worked and passed --no-default-features as expected, I can't wait for it to get stabilized ! \o/

**Comment by o0Ignition0o** [comment]
@daubaris could you please test again to make sure i can close this one? :)

**Comment by daubaris** [comment]
@o0Ignition0o yeah, I can confirm that it works with `--preview` flag
