### ISSUE TITLE
Run cargo-scout on unstaged added files

### ISSUE THREAD

**Issue by cbonaudo** [o0Ignition0o/cargo-scout#38]
Currently, cargo-scout is able to run on the staged modifed and added files, but only on the unstaged modified files (since the unstaged added files are created as untracked).

This behaviour is a bit incoherent with clippy's usage, where even untracked files are checked.

Ideally, we'd need clippy to run on untracked files.
The problem is that `git diff` cannot check untracked files as is.

**Comment by o0Ignition0o** [comment]
That's a great idea!

It seems like we can get a list of untracked files [using git ls-files](https://stackoverflow.com/questions/33254470/show-untracked-files-as-git-diff?lq=1)

It would definitely add some consistency ! 🎉

**Comment by o0Ignition0o** [comment]
Just got tricked while running cargo-scout while preparing #48 (Forgot to git add everything...)
