### ISSUE TITLE
Refactor git.rs sections

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#41]
[the git sections function is becoming more and more messy](https://github.com/o0Ignition0o/cargo-scout/blob/master/src/git.rs#L83). There is probably a way to refactor it and have a clean output.

Tests will allow us to refactor it, let's see if we can split it and do a better pattern matching.

**Comment by ebroto** [comment]
I think we can close this one, I forgot to link it in #46
