### ISSUE TITLE
quick win: enable clippy-preview unstable features behind a flag ?

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#45]
As explained in #36 and in this [neqo comment](https://github.com/mozilla/neqo/issues/150#issuecomment-564772044), an unstable feature available on nightly only actually allows us to pass --no-default-features as expected, and to get relevant lints even if a build has already been done.

We might want to add a --preview flag that would allow us to run a nightly version and make the tool much more useful while the features we need are being stabilized.

The correct command we can already run on nightly `cargo +nightly clippy-preview -Z unstable-options --no-default-features -- -W clippy::pedantic` behaves exactly the way we wish ! 🎉

**Comment by daubaris** [comment]
I can take this one on

**Comment by o0Ignition0o** [comment]
Sure, thank you for doing that !
