### ISSUE TITLE
Suggestion: move tests to a separate location

### ISSUE THREAD

**Issue by daubaris** [o0Ignition0o/cargo-scout#54]
The project is getting bigger and it would be a good idea to split separate parts (tests in this case) into a separate location.

**Comment by o0Ignition0o** [comment]
That's a very good idea !
Do you think it would make more sense to keep them in module subfolders, or would you rather go with a separate tests/ folder at the root ?

**Comment by daubaris** [comment]
I think a separate `tests` folder at root would do just fine.

**Comment by o0Ignition0o** [comment]
Sounds good to me, maybe unit tests and scoping will comme in handy someday, but we can figure it out later on :)
Wanna give it a try ? :)

**Comment by daubaris** [comment]
Sure. Most probably will add it tomorrow :slightly_smiling_face:

**Comment by o0Ignition0o** [comment]
Take your time, thanks for doing it ! 🎉

**Comment by ebroto** [comment]
I'm sorry to disagree, but doesn't this go against the [convention](https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests) on unit test organization? Moreover, I think that the `tests` directory is reserved for integration tests and has a specific [behavior](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-directory), namely each file being treated as a different crate.

**Comment by o0Ignition0o** [comment]
Oh that's interesting, maybe it would make sense to figure out which tests in the crate are unit ones, and which ones are integration tests, and make sure the line is correctly drawn in cargo-scout ?

Regardless of the direction we will choose, I think we could document it.
I was considering adding a contributing.md file explaining how the code is structured and what the reasoning behind it is, it might be a good opportunity to do it.

**Comment by ebroto** [comment]
If I'm not mistaken all of our current tests are unitary. I think that to be able to have integration tests for a binary crate the behavior in `main.rs` must be split in a `lib.rs` first.

Totally agree with the CONTRIBUTING file, that would help newcomers :)

**Comment by o0Ignition0o** [comment]
Well the line gets a bit thinner in git.rs (depending on the definition of unit tests) because we create an actual git repo etc.
Maybe we could keep these as "unit tests" and we will someday spawn a git tmp folder and a cargo project in it etc.

**Comment by ebroto** [comment]
Indeed that one is debatable :) 

Yep as I understand it an integration test for cargo-scout would include a full-blown rust project (maybe with workspaces) to test that we get the lints properly.

**Comment by daubaris** [comment]
Maybe this issue could be closed and reopened when we actually do have integrations tests then?

**Comment by o0Ignition0o** [comment]
Hmm ok, let's keep it in mind for when we will add integration tests then !
I have a nice use case for it, which is #53 imo, I'll try to write a failing test when I have a bit of time
