### ISSUE TITLE
impl std::error::Error for cargo scout Error

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#58]
As mentionned [in this comment](https://github.com/o0Ignition0o/cargo-scout/pull/57#discussion_r359507931) cargo scout Error is expected to [implement std::error::Error](https://doc.rust-lang.org/std/error/trait.Error.html).

This is something that would probably only require us to [add an impl Display](https://doc.rust-lang.org/std/fmt/trait.Display.html) to it :)

**Comment by undef1nd** [comment]
Plz, assign this one to me. Thanks!

**Comment by o0Ignition0o** [comment]
Yay!
Let me know if you have any question ! 🎉

**Comment by o0Ignition0o** [comment]
I've had a bit of a look at this issue, and here's something pretty cool! 

As explained in the [Error trait description](https://doc.rust-lang.org/std/error/trait.Error.html) `Errors must describe themselves through the Display and Debug traits, and may provide cause chain information.`, so it means it could be implemented automagically if we add an `impl Display for Error`:
```
impl Display for Error {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        // our impl happens here 
    }
}
// The magic happens here
impl std::error::Error for Error {}
```

We also want to have the std error trait in scope, but not callable (it would cause conflicts with our Error enum) eg: 

```
// We want the trait to be in scope,
// But we don't want it to cause conflicts
// with the enum name.
use std::error::Error as _;
```

One drawback of it is that it won't implement the cause() function on its own, so we might want to provide it ourselves.

So this issue has actually two parts:
- Implement Display for Error
- Implement std::error::Error for Error (with a cause() function)

Both steps can be split in separate issues, or tackled in this one, depending on how hard it would be, and how long it would take (and if you wanna do it of course :D)

Please let me know what you think 🎉

**Comment by ebroto** [comment]
Just to add my 2 cents, I think we should implement [source](https://doc.rust-lang.org/std/error/trait.Error.html#method.source) instead of [cause](https://doc.rust-lang.org/std/error/trait.Error.html#method.cause) as the latter has been deprecated.

We could also think about using the great [thiserror](https://github.com/dtolnay/thiserror) to reduce the boilerplate of the `From` implementations, getting also the `source` implementation for free, though we should think if we want to add a dependency for this :)

**Comment by o0Ignition0o** [comment]
Oh that’s an excellent crate !
It would even solve the code coverage 🎉
