### ISSUE TITLE
Add some tests to error.rs

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#70]
There currently isn't any test for the error.rs file [as we can see here](https://codecov.io/gh/o0Ignition0o/cargo-scout/src/696e6ae34f45f39f0c96e5c17685bd4dcfa0d55d/cargo-scout-lib/src/error.rs)

Once #58 is complete, cargo-scout errors will implement [the error trait](https://doc.rust-lang.org/std/error/trait.Error.html).

This issue will become a nice first contribution, and a good step to learn [how to write tests in rust](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

If anyone wants to pick this one up, please let me know !
I'll happily answer any questions, and / or have a chat with you :D 

# How to proceed ? 

As you can see [in our already existing tests](https://github.com/o0Ignition0o/cargo-scout/blob/master/cargo-scout-lib/src/linter/clippy.rs#L171)

there are 3 Phases:
- Setup: This is the phase where we prepare everything before running our tests. It involves creating our structures, preparing them to work as expected, and set up our expected result (this is the most important step)
- Run: This is the phase where we actually call the function we're trying to test.
- Assert: This is the phase where we make sure our actual result equals the expected one.

# How to add tests to error.rs ?

Let's pretend we want to cover Error generation from String.
Here's a list of the three phases we want to add in this context:
- Setup: We first want to create a String.
- Run: We now create an error from the string
- Assert: We can make sure the error description matches the expected one.

Here's what the test for a Command error would look like : 

```
#[cfg(test)]
mod scout_tests {
    use super::*;
    #[test]
    fn test_command_error() {
        // Setup
        let test_string_error = "this is a test error".to_string();
        let expected_error = Error::Command(test_string_error.clone());

        // Run
        // into() will call From<String> implicitely
        let actual_error: Error = test_string_error.into();

        // Assert
        assert_eq!(expected_error.description(), actual_error.description());
    }
}
```

If you want to wee me write more tests, have a look at [this video](https://www.youtube.com/watch?v=vrCuCnHYep0) :)

**Comment by laysauchoa** [comment]
ah, this has been merged already.

**Comment by o0Ignition0o** [comment]
Hey @laysauchoa !

It has indeed been merged already, but I would love to find other e-easy pull requests you could grab and I can help you with!

Could you please let me know a bit more about what you would like to learn ? I’ll figure something out :)
