### ISSUE TITLE
Diff against HEAD by default instead of master

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#76]
As mentioned by @ebroto [in this comment](https://github.com/o0Ignition0o/cargo-scout/pull/74#issuecomment-573458734_), it would probably make much more sense to diff against HEAD instead of master by default.

It would require us to change [the default value of the branch option](https://github.com/o0Ignition0o/cargo-scout/blob/master/cargo-scout/src/main.rs#L27) from master to HEAD.

We would probably need to update the README.md file, and perhaps some documentation and tests as well.

**Comment by undef1nd** [comment]
Taking it!

**Comment by o0Ignition0o** [comment]
Yay thanks for doing it ! 🎉
