### ISSUE TITLE
pass --all-features to clippy

### ISSUE THREAD

**Issue by o0Ignition0o** [o0Ignition0o/cargo-scout#9]
cargo-scout should be allowed to be passed --all-features and pass it to clippy

A live stream on how to fix #11, which almost requires the same steps as fixing this issue is available here https://youtube.com/watch?v=vrCuCnHYep0 :)

If someone would like to work on it, please let me know and I'll do anything I can to ease the process 🎉

**Comment by undef1nd** [comment]
@o0Ignition0o , I'll take this one. Thanks!

**Comment by o0Ignition0o** [comment]
Wow awesome :D If you have any question please let me know :)

**Comment by undef1nd** [comment]
Thanks, I will. Btw, it's not possible to send you a message on twitter :)

**Comment by o0Ignition0o** [comment]
oh thats weird ! I'm sending you a dm!
